### ISSUE TITLE
Polygon region selection

### ISSUE THREAD

**Issue by ds2268** [girder/slicer_cli_web#149]
Is it possible to select ROI as a polygon and not only a rectangular ROI? In the Slicer documentation it seems like only rectangular ROI is supported?

Use-case: Pathologist selects a more detailed polygon region to perform an automated analysis, instead of just rectangular ROI.

Can this be achieved using DSA and slicer_cli_web?

**Comment by manthey** [comment]
There isn't currently a direct interface to do this.  The slicer_cli_web protocol allows passing arbitrary data to a command, so you'd have to decide on a format for the polygon (for instance, do you allow holes or just a closed polygon).  The UI would be easy to extend -- it would just be a matter of calling the polygon annotation instead of the rectangle annotation.

Any algorithm that accepts an ROI would need to handle receiving the polygon and using it.

**Comment by ds2268** [comment]
Can you give me some pointers on how to include that? I understand that there are problems then with polygons with holes etc., but this can be handled then inside the execution program to for example fail the execution in such case. I just want to have the capability for the user to select and pass a polygon instead of a rectangular ROI. What do I need to change to have this capability? Slicer region schema explicitly mentions that it only supports rectangular ROI. Is there a  need then to have a custom XML schema for this kind of region?

**Comment by manthey** [comment]
The code is a bit scattered to implement this fully.  The slicer_cli_web specifies a "region" element in the schema.  This is simply a string that consuming clis expect to be a comma-separated list of coordinates (left, top, width, height).  Looking at the schema docs, this doesn't seem to match correctly.  I think you wouldn't have to make any change to the schema (since it looks like we are just passing through a string), though it would be more correct to make a new schema element.

The UI is actually invoked in large_image: https://github.com/girder/large_image/blob/master/girder_annotation/girder_large_image_annotation/web_client/views/imageViewerWidget/geojs.js#L610  From a UI perspective, just changing "rectangle" to "polygon" would let you draw a polygon.  The callback would then store a coordinates in whatever manner you chose.

If you want to specify a new type of element (other than a region) for the schema, this would require extending the slicer_cli specification, which would involve a greater change.

Without much consideration, I might use the existing region and specify the region string as something like [[[x,y],[x,y],[x,y],...],<additional polygons or holes>].  This wouldn't work for algorithms expecting left.top,width,height, but a check if the string starts with [ would be easy to distinguish between the different cases.

**Comment by ds2268** [comment]
@manthey you probably meant to change this to "polygon":

https://github.com/girder/large_image/blob/master/girder_annotation/girder_large_image_annotation/web_client/views/imageViewerWidget/geojs.js#L655

and then basically modify this part, in order to return  [[[x,y],[x,y],[x,y],...],] like object:

https://github.com/girder/large_image/blob/master/girder_annotation/girder_large_image_annotation/web_client/views/imageViewerWidget/geojs.js#L664-L674

Correct me, if I am wrong. 

Do you see an easy approach where I could use both? That is, the user has a selection box to choose between bbox/polygon which is then updated in region selection UI?

**Comment by manthey** [comment]
We need a way for the xml to specify that a region could be a rectangle and/or a polygon (and, if we wanted to be strictly compatible with the original slicer_cli specification, this should probably also include the point and radius form, too).

The changes to this repo will be something like I just checked in to the branch `polygon-regions`.  This adds a `shapes` attribute to the `region` element that is a comma-separated list possibly containing default, rectangle, and polygon.  There would need to be corresponding changes to the girder large_image client code to handle clicking on the polygon button and storing the appropriate value in the region parameter.  I'm open to doing this a different way.  And, ideally, the branch could use documentation and tests.

**Comment by ds2268** [comment]
That would be a perfect solution @manthey. I have currently resorted to basically first drawing a new polygon outside the task UI. Then in the task, I check if the BBOX region is not specified (i.e. -1, -1, -1, -1) and if not, I use girder API to get current image annotations (through args.inputFileName -> itemID -> annotation/itemID) and look for the polygons in annotations and execute the task on all the found polygons. This is far from optimal, but it does the job done for now.

I have exactly no expertise in JS/frontend development so unfortunately, I cannot help with the implementation, but I am more than happy to test it out and provide feedback.

Let's keep this issue open and notify me when this will be ready for a test drive :) Thanks!!

**Comment by manthey** [comment]
See the `polygon-regions` branch in each of this repo, large_image, and HistomicsUI for support.  Since the slicer_cli doesn't have a nested vector datatype, I've chosen to have polygons represented as vectors of x,y,x,y,... where there are at least 8 values (for triangles, repeat a vertex).  If you need holes or multiple polygons, they can be separated by -1,-1 (which means that if you need that coordinate in your polygon and you support multiple polygons or holes, you'll need to add an epsilon to one or the other).

**Comment by ds2268** [comment]
I managed to make it work, but it's a bit ugly. I needed to go to the docker container and change the branch of large-image to "polygon-regions" and then rebuild the HistomicsUI. With deploy.sh (by extending it also with large-image -> check post above), it doesn't work for me.

For the polygon integration, I have already integrated it, and looks great! I will test it thoroughly and report back if any issues. Thanks for adding this feature!

**Comment by ds2268** [comment]
@manthey Any suggestion on the "refresh rate" after executing the task? This is a real bottleneck in real-world usage as it sometimes doubles or triples the amount of time needed to display the resulting overlays, despite the task finishing way earlier. Is there some hookup missing to refresh HistomicsUI right when execution finishes?

**Comment by manthey** [comment]
Polygon regions were added in #164 and others.
