### ISSUE TITLE
use docker image from private registry

### ISSUE THREAD

**Issue by rogertrullo** [girder/slicer_cli_web#215]
Hi, when importing the docker image, I do not see an option to login on a private docker registry. What would be the best way to handle this?
Thanks

**Comment by manthey** [comment]
I _think_ (but haven't done it), that you have to authorize the private repo on the system running girder (and also the one running girder_worker, if they are different).  You'd do `docker login <private docker regsitry>` on that system, and then you could pull from the registry using those login credentials. 

If we needed a way to authorize this from the Girder UI, we'd have to add an equivalent command to the remote worker plugin -- but that requires knowing how to present the authentication for the registry, which could vary).

**Comment by manthey** [comment]
This has been documented a little at https://github.com/DigitalSlideArchive/digital_slide_archive/blob/master/devops/dsa/docker-compose.yml#L32-L37.

This recommends that, assuming you are using a docker deployment, you authenticate the private registry on the host machine(s) running girder and girder_worker, then use docker_compose to pass through those credentials.  This avoids having to reauthenticate when updating docker containers.

You can pull with the appropriate registry references.  For example, a docker image will be references `<registry host>:<registry port>/<docker image name and tag>`.  As an example, `private_registry:5000/dsarchive/histomicstk:latest` would pull from the private_registry rather than docker hub.
